name = "CrystalStructures"
uuid = "7fb32940-d43e-44e6-86bb-79144c2b0943"
authors = ["Brandon Flores <bsflores@wisc.edu>"]
version = "0.1.0"

[deps]
Crystalline = "ae5e2be0-a263-11e9-351e-f94dad1eb351"
